# Generated by Django 3.1.4 on 2020-12-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headlinelisting',
            old_name='assessed',
            new_name='accessed',
        ),
    ]
